platform :ios, '9.3'

target 'LoyaltyStore' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoyaltyStore
  
  # Firebase
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  
  pod 'EstimoteSDK'
end
