platform :ios, '11.0'

target 'NFCStamps' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NFCStamps
    pod 'EstimoteSDK'

end
